const INITIAL = 'initial';
const IDENTIFIERS = 'identifiers';
const RESERVED_WORDS = 'reservedWords';
const DELIMITERS = 'delimiters';
const LOGICAL_OPERATORS_NOT = 'logicalOperatorsNot';
const LOGICAL_OPERATORS_PARTIAL = 'logicalOperatorsPartial';
const LOGICAL_OPERATORS = 'logicalOperators';
const RELATIONAL_OPERATORS_SIMPLE = 'relationalOperatorsSimple';
const RELATIONAL_OPERATORS = 'relationalOperators';
const ARITHMETIC_OPERATORS = 'arithmeticOperators';
const ARITHMETIC_OPERATORS_SLASH = 'arithmeticOperatorsSlash';
const ARITHMETIC_OPERATORS_PLUS = 'arithmeticOperatorsPlus';
const ARITHMETIC_OPERATORS_DOUBLE_PLUS = 'arithmeticOperatorsDoublePlus';
const ARITHMETIC_OPERATORS_MINUS = 'arithmeticOperatorsMinus';
const ARITHMETIC_OPERATORS_DOUBLE_MINUS = 'arithmeticOperatorsDoubleMinus';
const NUMBERS = 'numbers';
const NUMBERS_POINT = 'numbersPoint';
const NUMBERS_FLOAT = 'numbersFloat';
const STRING_START_DOUBLE_QUOTES = 'stringStartDoubleQuotes';
const STRING_MIDDLE = 'stringMiddle';
const STRING_END_DOUBLE_QUOTES = 'stringEndDoubleQuotes';
const CHARACTER_START_SINGLE_QUOTES = 'characterStartSingleQuotes';
const CHARACTER_MIDDLE = 'characterMiddle';
const CHARACTER_END_SINGLE_QUOTES = 'characterEndSingleQuotes';
const LINE_COMMENT_PERCENT = 'lineCommentPercent';
const LINE_COMMENT_MIDDLE = 'lineCommentMiddle';
const LINE_COMMENT_LINE_BREAK = 'lineCommentLineBreak';
const BLOCK_COMMENT_START_HASH = 'blockCommentStartHash';
const BLOCK_COMMENT_MIDDLE = 'blockCommentMiddle';
const BLOCK_COMMENT_END_HASH = 'blockCommentEndHash';
const BLOCK_COMMENT_END_SLASH = 'blockCommentEndSlash';
const ERROR_INVALID_CHARACTER = 'invalidCharacter';
const ERROR_NUMBERS_POINT = 'errorNumbersPoint';
const ERROR_BLOCK_COMMENT_NOT_CLOSED = 'errorBlockCommentNotClosed';
const ERROR_STRING_NOT_CLOSED = 'errorStringNotClosed';
const ERROR_CHARACTER_NOT_CLOSED = 'errorCharacterNotClosed';

module.exports = {
  INITIAL,
  IDENTIFIERS,
  RESERVED_WORDS,
  DELIMITERS,
  LOGICAL_OPERATORS_NOT,
  LOGICAL_OPERATORS_PARTIAL,
  LOGICAL_OPERATORS,
  RELATIONAL_OPERATORS_SIMPLE,
  RELATIONAL_OPERATORS,
  ARITHMETIC_OPERATORS,
  ARITHMETIC_OPERATORS_SLASH,
  ARITHMETIC_OPERATORS_PLUS,
  ARITHMETIC_OPERATORS_DOUBLE_PLUS,
  ARITHMETIC_OPERATORS_MINUS,
  ARITHMETIC_OPERATORS_DOUBLE_MINUS,
  NUMBERS,
  NUMBERS_POINT,
  NUMBERS_FLOAT,
  STRING_START_DOUBLE_QUOTES,
  STRING_MIDDLE,
  STRING_END_DOUBLE_QUOTES,
  CHARACTER_START_SINGLE_QUOTES,
  CHARACTER_MIDDLE,
  CHARACTER_END_SINGLE_QUOTES,
  LINE_COMMENT_PERCENT,
  LINE_COMMENT_MIDDLE,
  LINE_COMMENT_LINE_BREAK,
  BLOCK_COMMENT_START_HASH,
  BLOCK_COMMENT_MIDDLE,
  BLOCK_COMMENT_END_HASH,
  BLOCK_COMMENT_END_SLASH,
  ERROR_INVALID_CHARACTER,
  ERROR_NUMBERS_POINT,
  ERROR_BLOCK_COMMENT_NOT_CLOSED,
  ERROR_STRING_NOT_CLOSED,
  ERROR_CHARACTER_NOT_CLOSED,
}